import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import Navbar from '@/components/widgets/navbar';
import SessionWrapper from '@/components/session-wrapper';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Ecommerce With Mysql',
	description: 'Generated by ecommerce-with-mysql',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' /*suppressHydrationWarning*/>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Navbar />
				<SessionWrapper>{children}</SessionWrapper>
			</body>
		</html>
	);
}
